services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASS}'
            MYSQL_ROOT_HOST: '${DB_HOST}'
            MYSQL_DATABASE: '${DB_NAME}'
            MYSQL_USER: '${DB_USER}'
            MYSQL_PASSWORD: '${DB_PASS}'
        volumes:
            - 'mysql:/var/lib/mysql'
volumes:
    mysql:
        driver: local