-- Active: 1699462180782@@127.0.0.1@3306@gofriends

DROP DATABASE IF EXISTS gofriends;
CREATE DATABASE IF NOT EXISTS gofriends;
USE gofriends;
CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	nick VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;

CREATE TABLE followers (
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	follower_id INT NOT NULL,
	FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
	PRIMARY KEY(user_id, follower_id)
) ENGINE=INNODB;

CREATE TABLE posts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	content VARCHAR(300) NOT NULL,
	likes INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	author_id INT NOT NULL,
	FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=INNODB;
