-- Active: 1699462180782@@127.0.0.1@3306@gofriends

DROP DATABASE IF EXISTS gofriends;
CREATE DATABASE IF NOT EXISTS gofriends;
USE gofriends;
CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	nick VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;
